export const personalConfig = {
  name: 'Dogu Yilmaz',
  title: 'Software Developer / Computer Engineer',
  contact: {
    phone: '+90 551 958 1985',
    email: 'dogukyilmaz@gmail.com',
    github: 'doguyilmaz',
    website: 'doguyilmaz.com',
  },
  languages: [
    { name: 'Turkish', level: 'Native' },
    { name: 'English', level: 'Professional Proficiency' },
  ],
  skills: [
    'JavaScript',
    'TypeScript',
    'React',
    'Next.js',
    'React Native',
    'Redux',
    'Zustand',
    'Tailwind',
    'Astro',
    'Framer Motion',
    'Figma',
    'Node.js',
    'Express',
    'Go',
    'ElysiaJS',
    'Bun',
    'MongoDB',
    'PostgreSQL',
    'Prisma',
    'Supabase',
    'PocketBase',
    'Firebase',
    'Redis',
    'Docker',
    'Highcharts',
    'Visx',
    'ApexCharts',
    'Kepler.gl',
    'Carto',
    'Deck.gl',
    'MapGL',
    'Mapbox',
    'Leaflet',
    'Jest',
    'Vitest',
    'Cypress',
    'Playwright',
  ],
};
